### ISSUE TITLE
Nulmeting: Toetsing op onbekende collecties

### ISSUE THREAD

**Issue by StichtingRIONED** [StichtingRIONED/GWSW#13]
**RIONED (20180214):**
Toetsing op "gerefereerd object binnen   collectie", de opmerkingen "collectie niet gedefinieerd"   alleen in combi met GWSW Totaal (query splitsen?)

**Comment by MarinusVonhof** [comment]
GWSW Apps aangepast (20190818), dataset wordt nu altijd aan GWSW Totaal gekoppeld.
