### ISSUE TITLE
Gedammerde putten, hoe deze te noemen?

### ISSUE THREAD

**Issue by ChantalSchaefer** [StichtingRIONED/GWSW#27]
Als een leiding gedammerd is inclusief de putten, hoe moet je dan de putten gaan benoemen?

**Comment by MarinusVonhof** [comment]
Is opgenomen in de wijzigingsvoorstellen voor het GWSW. Ter behandeling door de werkgroep GWSW-Basis, daarom hier dit issue gesloten.
