### ISSUE TITLE
Melding Collectie onbekend in deze CFK: Stromingsrichting

### ISSUE THREAD

**Issue by ChantalSchaefer** [StichtingRIONED/GWSW#28]
Bij de melding dat de collectie onbekend is ivm stromingsrichting. Is het mogelijk dat dit per leiding wordt weergegeven? Nu staat alleen het aantal voor ieder type aspect en niet welke leiding het betreft.

**Comment by MarinusVonhof** [comment]
Deze melding is ook algemeen bedoeld. De collectie "stromingsrichting" is onbekend binnen de gebruikte conformiteitsklasse. Dat staat even los van de objecten waarvoor de collectie gebruikt wordt.
