### ISSUE TITLE
Nulmeting: Waarde te groot, kan deze aangepast worden?

### ISSUE THREAD

**Issue by ChantalSchaefer** [StichtingRIONED/GWSW#29]
bij bergingsleiding en bijzondere put constructie kan de waarde groter zijn dan de nu aangegeven maximum van 4000. kan deze waarde aangepast worden?

**Comment by MarinusVonhof** [comment]
De wens om grenswaarden te kunnen variëren werd ook tijdens het laatste GWSW Advies overleg geopperd. In de ontologie, waarin grenswaarden per kenmerk (bijvoorbeeld Leidinglengte) worden opgegeven is dit lastiger te verwerken. Waarschijnlijk wel te doen via maatwerk in GWSW Apps, onderzoeken dus.

**Comment by MarinusVonhof** [comment]
Dit issue overlapt met issue #11, commentaar samengevoegd, dit issue sluiten
