### ISSUE TITLE
Omzetting materiaalcodes in Orox.ttl

### ISSUE THREAD

**Issue by JenLDatamanagement** [StichtingRIONED/GWSW#34]
Bij de export naar .ttl in RioGL worden bepaalde materiaalcodes foutief omgezet. Een leiding met code HDPE (K) wordt bijvoorbeeld omgezet in Koper. 

![materiaal1](https://user-images.githubusercontent.com/48240865/53817740-798cde80-3f66-11e9-9458-55f746822fd3.png)

![materiaal2](https://user-images.githubusercontent.com/48240865/53817815-be187a00-3f66-11e9-96cd-43d145d682ea.png)

**Comment by EwoutZwolsman** [comment]
De vraag is even hoe dit voorkomen kan worden. Ik weet dat er in Kikker de optie bestaat om bepaalde materiaalcodes toe te kennen, voor RioGL ken ik deze optie niet.

**Comment by MarinusVonhof** [comment]
Dit is een vraag voor Sweco, de Obsurv/RioGL-leverancier. Maar namens Sweco :) kan ik wel meegeven dat de code "K" in RioGL normaal voor "Koper" is gereserveerd. De code "N" is gereserveerd voor "PE divers", die zou beter aansluiten. Maar via omzettingstabel dCodConv.txt kun je de gebruikte code "K" ook doorverwijzen naar de code "N". Dat zou deze problemen moeten oplossen, anders wordt het een issue voor Sweco.

**Comment by EricOosterom** [comment]
Afgehandeld, lijkt me.
