### ISSUE TITLE
Doorlatende leiding

### ISSUE THREAD

**Issue by JenLDatamanagement** [StichtingRIONED/GWSW#35]
Waaronder valt een doorlatende leiding in de soortenboom? (deze opent niet)

![image](https://user-images.githubusercontent.com/48240865/55467664-0ed0d080-5602-11e9-92de-4e5221dc53cf.png)

**Comment by MarinusVonhof** [comment]
Doorlatende leiding is een collectie (Drain, Infiltratieriool) maar verschijnt inderdaad ook niet als collectie. Dat wordt in de volgende versie gecorrigeerd.
