### ISSUE TITLE
GWSW.hydx: Inwendige afmetingen berekenen

### ISSUE THREAD

**Issue by StichtingRIONED** [StichtingRIONED/GWSW#37]
De HydX download aanpassen op inwendige afmetingen. In de HydX-definitie is die aangepast, de app is hierop nog niet aangepast. Geldt alleen voor kunststof leidingen, gebruik (bij voorkeur) de wanddikte of SDR Waarde (nieuw in versie 1.5)

**Comment by MarinusVonhof** [comment]
GWSW Apps hierop aangepast. Inwendige afmetingen worden berekend zodra materiaal-code = PVC of HPE
